{"version":"3.7.1","messages":["\nAn error occurred while loading ./spec/sinatra_logging_in_and_out_spec.rb.\n\u001b[31mFailure/Error: \u001b[0mload_dependency(file) { result = \u001b[32msuper\u001b[0m }\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mSyntaxError:\u001b[0m\n\u001b[31m  /home/fantastic-path-1139/sinatra-logging-in-and-out-online-web-pt-051319/spec/sinatra_logging_in_and_out_spec.rb:109: syntax error, unexpected end, expecting end-of-input\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'\u001b[0m\n","Run options: include {:focus=\u003etrue}","\nAll examples were filtered out; ignoring {:focus=\u003etrue}"],"examples":[],"summary":{"duration":0.000417541,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}